server:
  port: 8080
spring:
  application:
    name: online-store
  datasource:
    url: jdbc:postgresql://localhost:5432/online_store
    username: postgres
    password: qweqwe
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
    format_sql: true
    ddl-auto: validate
  liquibase:
    default-schema: public
    change-log: classpath:db/changelog/db.changelog-master.yaml
    parameters:
      admin_email: ${ADMIN_EMAIL:admin@sys.com}
      admin_password_hash: ${ADMIN_PASSWORD_HASH:$2a$10$Fwv9u80TU/Zzm95EbSbBueMU67FJtKr0XrQfHnvbl3z8aOPsl.y0C}
  thymeleaf:
    cache: false
  template:
    cache: false
  mvc:
    hidden-method:
      filter:
        enabled: true
  logging:
    level:
      org.springframework.security: DEBUG
      online-store: DEBUG
      org.springframework.amqp: DEBUG
  rabbitmq:
    port: 5672
    username: guest
    password: guest
queue.name: MainQueue