server:
  port: 8080
spring:
  application:
    name: online-store
  datasource:
    url: jdbc:postgresql://localhost:5432/online_store
    username: postgres
    password: qweqwe
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
    format_sql: true
    ddl-auto: validate
  liquibase:
    default-schema: public
    change-log: classpath:db/changelog/db.changelog-master.yaml
  thymeleaf:
    cache: false
  mvc:
    hidden method:
      filter:
        enabled: true